import ProtectedRoute from "@/components/auth/ProtectedRoute";
import { Role } from "@/types/role";
import { FileText, TrendingUp, Users, Clock, Download } from "lucide-react";

export default function ReportsPage() {
  // Mock Data
  const stats = [
    { label: "Total Headcount", value: "142", trend: "+12% this year", icon: Users, color: "blue" },
    { label: "Avg. Attendance", value: "94%", trend: "-2% this month", icon: Clock, color: "emerald" },
    { label: "Pending Leaves", value: "8", trend: "Needs review", icon: FileText, color: "amber" },
  ];

  const departmentData = [
    { dept: "Engineering", count: 45, percentage: 80 },
    { dept: "Sales", count: 32, percentage: 60 },
    { dept: "Marketing", count: 20, percentage: 40 },
    { dept: "HR & Ops", count: 15, percentage: 30 },
  ];

  return (
    // Restricted to HODs and above
    <ProtectedRoute allowedRoles={[Role.SUPER_ADMIN, Role.ADMIN, Role.MANAGEMENT, Role.HOD]}>
      <div className="p-8 max-w-7xl mx-auto w-full">
        
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4">
          <div>
            <h1 className="text-2xl font-bold text-slate-900">Analytics & Reports</h1>
            <p className="text-sm text-slate-500 mt-1">Organization metrics, attendance tracking, and exports.</p>
          </div>

          <button className="flex items-center gap-2 bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 px-4 py-2 rounded-xl text-sm font-medium transition-colors shadow-sm">
            <Download className="h-4 w-4" />
            Export CSV
          </button>
        </div>

        {/* Top Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          {stats.map((stat, i) => (
            <div key={i} className="bg-white border border-slate-100 rounded-2xl p-6 shadow-[0_2px_10px_rgb(0,0,0,0.02)]">
              <div className="flex items-center justify-between mb-4">
                <div className={`h-10 w-10 rounded-xl flex items-center justify-center bg-${stat.color}-50 text-${stat.color}-600`}>
                  <stat.icon className="h-5 w-5" />
                </div>
                <TrendingUp className={`h-4 w-4 text-${stat.color}-500 opacity-50`} />
              </div>
              <h3 className="text-2xl font-bold text-slate-900">{stat.value}</h3>
              <div className="flex items-center justify-between mt-1">
                <p className="text-sm font-medium text-slate-500">{stat.label}</p>
                <p className="text-xs text-slate-400">{stat.trend}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Minimalist Tailwind Data Visualization */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          
          {/* Department Headcount "Chart" */}
          <div className="bg-white border border-slate-100 rounded-2xl p-6 shadow-[0_2px_10px_rgb(0,0,0,0.02)]">
            <h2 className="font-semibold text-slate-800 mb-6">Headcount by Department</h2>
            <div className="space-y-5">
              {departmentData.map((data, i) => (
                <div key={i}>
                  <div className="flex justify-between text-sm mb-2">
                    <span className="font-medium text-slate-700">{data.dept}</span>
                    <span className="text-slate-500">{data.count} employees</span>
                  </div>
                  <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-blue-500 rounded-full transition-all duration-1000" 
                      style={{ width: `${data.percentage}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Recent Report Exports Mockup */}
          <div className="bg-white border border-slate-100 rounded-2xl p-6 shadow-[0_2px_10px_rgb(0,0,0,0.02)]">
            <h2 className="font-semibold text-slate-800 mb-6">Recent Reports Generated</h2>
            <div className="space-y-4">
              {[1, 2, 3].map((item) => (
                <div key={item} className="flex items-center justify-between p-4 rounded-xl border border-slate-100 hover:border-blue-100 hover:bg-blue-50/50 transition-colors cursor-pointer group">
                  <div className="flex items-center gap-3">
                    <div className="h-10 w-10 rounded-lg bg-slate-50 group-hover:bg-blue-100 flex items-center justify-center text-slate-400 group-hover:text-blue-600 transition-colors">
                      <FileText className="h-5 w-5" />
                    </div>
                    <div>
                      <p className="text-sm font-medium text-slate-900">Q3 Attendance Summary</p>
                      <p className="text-xs text-slate-500">Generated by Admin • Oct 15</p>
                    </div>
                  </div>
                  <Download className="h-4 w-4 text-slate-300 group-hover:text-blue-500" />
                </div>
              ))}
            </div>
          </div>

        </div>

      </div>
    </ProtectedRoute>
  );
}