-- Employees without a known email (bulk import) no longer get a fabricated
-- "@employee.import.local" placeholder — email is left NULL instead.
-- The existing @@unique([email, organizationId]) index is unaffected: Postgres
-- treats each NULL as distinct, so multiple employees without an email in the
-- same org do not collide.
ALTER TABLE "Employee" ALTER COLUMN "email" DROP NOT NULL;

-- Clean up placeholder addresses generated by earlier imports (User.email was
-- already nullable, so this is safe on both tables).
UPDATE "Employee" SET "email" = NULL WHERE "email" LIKE '%@employee.import.local';
UPDATE "User" SET "email" = NULL WHERE "email" LIKE '%@employee.import.local';
