-- CreateEnum
CREATE TYPE "KaizenTrigger" AS ENUM (
    'PROBLEM_NOTICED',
    'IMPROVEMENT_OPPORTUNITY_NOTICED',
    'ALERT_ACTION_REQUIRED',
    'ABNORMALITY_ACTION_REQUIRED',
    'EMPLOYEE_SUGGESTION_OR_IDEA',
    'AUDIT_OR_GEMBA_WALK_OBSERVATION',
    'CUSTOMER_COMPLAINT_OR_FEEDBACK',
    'MANAGEMENT_INSTRUCTION_OR_FEEDBACK',
    'REPEAT_PROBLEM',
    'OTHER'
);

-- AlterTable
ALTER TABLE "Kaizen" ADD COLUMN "trigger" "KaizenTrigger";
ALTER TABLE "Kaizen" ADD COLUMN "triggerOther" TEXT;
